### ISSUE TITLE
what am i doing wrong

### ISSUE THREAD

**Issue by Bealze** [eminga/ts3updater#1]
-bash: root@svr1: command not found
root@svr1 [/home/ts3server/serverfiles]# ./ts3updater.sh                        New version available: 3.1.0
error: values is not defined
.mirrors | values[]
           ^^^^^^
1 compile error

curl: (3) <url> malformed
Checksum of downloaded file is incorrect!
root@svr1 [/home/ts3server/serverfiles]#

**Comment by eminga** [comment]
Sorry, I just saw your issue.
Looks like the downloaded server.json was corrupt. Did this happen again at a later point in time?

**Comment by eminga** [comment]
I found the reason for the error: A command used by the script is only supported by jq 1.4 or newer.
Thank you for reporting! I updated the README.md accordingly.
