### ISSUE TITLE
Prevent update script from overwriting a specific file

### ISSUE THREAD

**Issue by dt-flo** [eminga/ts3updater#4]
I would like to keep my "ts3server_startscript.sh" because i am using the ts3server.ini to configure my server instance. Is this supported?

**Comment by eminga** [comment]
Hi, I'm not sure if this is a good idea as this file might change in the future and not updating it might break the entire installation.

However, removing the write permissions from this file will probably prevent tar from overwriting it (the scipt uses tar to extract the new files and overwrite old files with the same name): `chmod -w ts3server_startscript.sh`
